haproxy:
  ports:
  - 80:80
  labels:
    io.rancher.loadbalancer.target.traefik: 80=8080
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  tty: true
  image: rancher/load-balancer-service
  links:
  - traefik:traefik
  stdin_open: true

traefik:
  ports:
  - 8000:8000/tcp
  - 8080:8080/tcp
  environment:
    CONF_INTERVAL: '60'
    TRAEFIK_HTTPS_ENABLE: 'false'
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.sidekicks: traefik-conf
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  tty: true
  image: rawmind/alpine-traefik:1.0.1-1
  volumes_from:
  - traefik-conf

traefik-conf:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  tty: true
  image: rawmind/rancher-traefik:0.3.4
  net: none
